# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Spring PetClinic Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-app:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
  
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-      
          
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
#     - name: Nexus Repository Publisher for GitHub Actions
#       uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
#       with:
#         serverUrl: http://nexus:8081
#         username: admin
#         password: ${{ secrets.nexus_password }}
#         format: maven2
#         repository: maven-releases
#         coordinates: groupId=com.example artifactId=app version=1.0.0
#         assets: extension=jar
#         filename: ./target/spring-petclinic-2.4.5.jar

